In [ ]:
import pandas as pd
import numpy as np

from google.colab import files

In [ ]:
!pip install -q kaggle

In [ ]:
# uploaded = files.upload()

In [ ]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle

!chmod 600 /root/.kaggle/kaggle.json

In [ ]:
!kaggle datasets download -d osmi/mental-health-in-tech-survey

  0% 0.00/48.8k [00:00<?, ?B/s]
100% 48.8k/48.8k [00:00<00:00, 37.8MB/s]


In [ ]:
!unzip -q /content/mental-health-in-tech-survey.zip -d .

In [ ]:
df = pd.read_csv('/content/survey.csv')

In [ ]:
df.head(3)

Timestamp  Age  Gender        Country state self_employed  \
0  2014-08-27 11:29:31   37  Female  United States    IL           NaN   
1  2014-08-27 11:29:37   44       M  United States    IN           NaN   
2  2014-08-27 11:29:44   32    Male         Canada   NaN           NaN   

  family_history treatment work_interfere    no_employees  ...  \
0             No       Yes          Often            6-25  ...   
1             No        No         Rarely  More than 1000  ...   
2             No        No         Rarely            6-25  ...   

                leave mental_health_consequence phys_health_consequence  \
0       Somewhat easy                        No                      No   
1          Don't know                     Maybe                      No   
2  Somewhat difficult                        No                      No   

      coworkers supervisor mental_health_interview phys_health_interview  \
0  Some of them        Yes                      No                 Maybe   
1            No         No                      No                    No   
2           Yes        Yes                     Yes                   Yes   

  mental_vs_physical obs_consequence comments  
0                Yes              No      NaN  
1         Don't know              No      NaN  
2                 No              No      NaN  

[3 rows x 27 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1259 entries, 0 to 1258
Data columns (total 27 columns):
 #   Column                     Non-Null Count  Dtype 
---  ------                     --------------  ----- 
 0   Timestamp                  1259 non-null   object
 1   Age                        1259 non-null   int64 
 2   Gender                     1259 non-null   object
 3   Country                    1259 non-null   object
 4   state                      744 non-null    object
 5   self_employed              1241 non-null   object
 6   family_history             1259 non-null   object
 7   treatment                  1259 non-null   object
 8   work_interfere             995 non-null    object
 9   no_employees               1259 non-null   object
 10  remote_work                1259 non-null   object
 11  tech_company               1259 non-null   object
 12  benefits                   1259 non-null   object
 13  care_options               1259 non-null   object
 14  wellness

In [ ]:
df.describe()

Age
count  1.259000e+03
mean   7.942815e+07
std    2.818299e+09
min   -1.726000e+03
25%    2.700000e+01
50%    3.100000e+01
75%    3.600000e+01
max    1.000000e+11

In [ ]:
df.shape

(1259, 27)

In [ ]:
df.isnull().sum()

Timestamp                       0
Age                             0
Gender                          0
Country                         0
state                         515
self_employed                  18
family_history                  0
treatment                       0
work_interfere                264
no_employees                    0
remote_work                     0
tech_company                    0
benefits                        0
care_options                    0
wellness_program                0
seek_help                       0
anonymity                       0
leave                           0
mental_health_consequence       0
phys_health_consequence         0
coworkers                       0
supervisor                      0
mental_health_interview         0
phys_health_interview           0
mental_vs_physical              0
obs_consequence                 0
comments                     1095
dtype: int64

In [ ]:
df = df.drop(columns = ['state', 'comments'])

In [ ]:
df.work_interfere.unique()

array(['Often', 'Rarely', 'Never', 'Sometimes', nan], dtype=object)

In [ ]:
print(df.work_interfere.value_counts())

Sometimes    465
Never        213
Rarely       173
Often        144
Name: work_interfere, dtype: int64


In [ ]:
# fill in the missing value in the work_interfere column with 'Sometimes' -- appears more often according to the results above

df['work_interfere'] = df['work_interfere'].fillna('Sometimes')
df[df.isna().any(axis=1)]

Timestamp  Age  Gender         Country self_employed  \
0   2014-08-27 11:29:31   37  Female   United States           NaN   
1   2014-08-27 11:29:37   44       M   United States           NaN   
2   2014-08-27 11:29:44   32    Male          Canada           NaN   
3   2014-08-27 11:29:46   31    Male  United Kingdom           NaN   
4   2014-08-27 11:30:22   31    Male   United States           NaN   
5   2014-08-27 11:31:22   33    Male   United States           NaN   
6   2014-08-27 11:31:50   35  Female   United States           NaN   
7   2014-08-27 11:32:05   39       M          Canada           NaN   
8   2014-08-27 11:32:39   42  Female   United States           NaN   
9   2014-08-27 11:32:43   23    Male          Canada           NaN   
10  2014-08-27 11:32:44   31    Male   United States           NaN   
11  2014-08-27 11:32:49   29    male        Bulgaria           NaN   
12  2014-08-27 11:33:23   42  female   United States           NaN   
13  2014-08-27 11:33:26   36    Male   United States           NaN   
14  2014-08-27 11:33:57   27    Male          Canada           NaN   
15  2014-08-27 11:34:00   29  female   United States           NaN   
16  2014-08-27 11:34:20   23    Male  United Kingdom           NaN   
17  2014-08-27 11:34:37   32    Male   United States           NaN   

   family_history treatment work_interfere    no_employees remote_work  ...  \
0              No       Yes          Often            6-25          No  ...   
1              No        No         Rarely  More than 1000          No  ...   
2              No        No         Rarely            6-25          No  ...   
3             Yes       Yes          Often          26-100          No  ...   
4              No        No          Never         100-500         Yes  ...   
5             Yes        No      Sometimes            6-25          No  ...   
6             Yes       Yes      Sometimes             1-5         Yes  ...   
7              No        No          Never             1-5         Yes  ...   
8             Yes       Yes      Sometimes         100-500          No  ...   
9              No        No          Never          26-100          No  ...   
10             No       Yes      Sometimes            6-25         Yes  ...   
11             No        No          Never         100-500         Yes  ...   
12            Yes       Yes      Sometimes          26-100          No  ...   
13            Yes        No          Never        500-1000          No  ...   
14             No        No          Never            6-25          No  ...   
15            Yes       Yes         Rarely          26-100          No  ...   
16             No       Yes      Sometimes          26-100         Yes  ...   
17             No       Yes      Sometimes            6-25          No  ...   

     anonymity               leave mental_health_consequence  \
0          Yes       Somewhat easy                        No   
1   Don't know          Don't know                     Maybe   
2   Don't know  Somewhat difficult                        No   
3           No  Somewhat difficult                       Yes   
4   Don't know          Don't know                        No   
5   Don't know          Don't know                        No   
6           No  Somewhat difficult                     Maybe   
7          Yes          Don't know                        No   
8           No      Very difficult                     Maybe   
9   Don't know          Don't know                        No   
10  Don't know          Don't know                        No   
11  Don't know          Don't know                        No   
12  Don't know  Somewhat difficult                       Yes   
13  Don't know          Don't know                        No   
14  Don't know       Somewhat easy                        No   
15  Don't know       Somewhat easy                        No   
16  Don't know           Very easy                     Maybe   
17  Don't know          Don't

In [ ]:
df.self_employed.unique()

array([nan, 'Yes', 'No'], dtype=object)

In [ ]:
print(df.self_employed.value_counts())

No     1095
Yes     146
Name: self_employed, dtype: int64


In [ ]:
# fill in the missing value in the self_employed column with 'No' -- appears more often according to the results above

df['self_employed'] = df['self_employed'].fillna('No')
df[df.isna().any(axis=1)]

Empty DataFrame
Columns: [Timestamp, Age, Gender, Country, self_employed, family_history, treatment, work_interfere, no_employees, remote_work, tech_company, benefits, care_options, wellness_program, seek_help, anonymity, leave, mental_health_consequence, phys_health_consequence, coworkers, supervisor, mental_health_interview, phys_health_interview, mental_vs_physical, obs_consequence]
Index: []

[0 rows x 25 columns]

In [ ]:
df.isnull().sum()

Timestamp                    0
Age                          0
Gender                       0
Country                      0
self_employed                0
family_history               0
treatment                    0
work_interfere               0
no_employees                 0
remote_work                  0
tech_company                 0
benefits                     0
care_options                 0
wellness_program             0
seek_help                    0
anonymity                    0
leave                        0
mental_health_consequence    0
phys_health_consequence      0
coworkers                    0
supervisor                   0
mental_health_interview      0
phys_health_interview        0
mental_vs_physical           0
obs_consequence              0
dtype: int64

In [ ]:
df.Gender.unique()

print(df.Gender.value_counts())

Male                                              615
male                                              206
Female                                            121
M                                                 116
female                                             62
F                                                  38
m                                                  34
f                                                  15
Make                                                4
Male                                                3
Woman                                               3
Cis Male                                            2
Man                                                 2
Female (trans)                                      2
Female                                              2
Trans woman                                         1
msle                                                1
male leaning androgynous                            1
Neuter                      

In [ ]:
def gender_awikwok(row):
  gender = row["Gender"].lower()
  if "f" in gender:
    return "Female"
  elif "w" in gender:
    return "Female"
  
  return "Male"

In [ ]:
df.Gender = df.apply(lambda row: gender_awikwok(row), axis=1)

In [ ]:
df.Gender.unique()

print(df.Gender.value_counts())

Male      1006
Female     253
Name: Gender, dtype: int64


In [33]:
df.Age.unique()

array([         37,          44,          32,          31,          33,
                35,          39,          42,          23,          29,
                36,          27,          46,          41,          34,
                30,          40,          38,          50,          24,
                18,          28,          26,          22,          19,
                25,          45,          21,         -29,          43,
                56,          60,          54,         329,          55,
       99999999999,          48,          20,          57,          58,
                47,          62,          51,          65,          49,
             -1726,           5,          53,          61,           8,
                11,          -1,          72])

In [37]:
df['Age'].replace([df['Age'][df['Age'] < 15]], np.nan, inplace = True)
df['Age'].replace([df['Age'][df['Age'] > 65]], np.nan, inplace = True)

df['Age'].unique()

array([37., 44., 32., 31., 33., 35., 39., 42., 23., 29., 36., 27., 46.,
       41., 34., 30., 40., 38., 50., 24., 18., 28., 26., 22., 19., 25.,
       45., 21., nan, 43., 56., 60., 54., 55., 48., 20., 57., 58., 47.,
       62., 51., 65., 49., 53., 61.])

In [ ]:
df['Age'].fillna(int(df['Age'].mean()), inplace=True)
df.head()

In [47]:
df['Age'].unique()

array([37., 44., 32., 31., 33., 35., 39., 42., 23., 29., 36., 27., 46.,
       41., 34., 30., 40., 38., 50., 24., 18., 28., 26., 22., 19., 25.,
       45., 21., 43., 56., 60., 54., 55., 48., 20., 57., 58., 47., 62.,
       51., 65., 49., 53., 61.])

In [ ]:
df.Country.unique()

print(df.Country.value_counts())

United States             751
United Kingdom            185
Canada                     72
Germany                    45
Ireland                    27
Netherlands                27
Australia                  21
France                     13
India                      10
New Zealand                 8
Poland                      7
Switzerland                 7
Sweden                      7
Italy                       7
South Africa                6
Belgium                     6
Brazil                      6
Israel                      5
Singapore                   4
Bulgaria                    4
Austria                     3
Finland                     3
Mexico                      3
Russia                      3
Denmark                     2
Greece                      2
Colombia                    2
Croatia                     2
Portugal                    2
Moldova                     1
Georgia                     1
Bahamas, The                1
China                       1
Thailand  

In [48]:
df = df.drop(columns = ['Timestamp', 'Country'])
df.head()

Age  Gender self_employed family_history treatment work_interfere  \
0  37.0  Female            No             No       Yes          Often   
1  44.0       M            No             No        No         Rarely   
2  32.0    Male            No             No        No         Rarely   
3  31.0    Male            No            Yes       Yes          Often   
4  31.0    Male            No             No        No          Never   

     no_employees remote_work tech_company    benefits  ...   anonymity  \
0            6-25          No          Yes         Yes  ...         Yes   
1  More than 1000          No           No  Don't know  ...  Don't know   
2            6-25          No          Yes          No  ...  Don't know   
3          26-100          No          Yes          No  ...          No   
4         100-500         Yes          Yes         Yes  ...  Don't know   

                leave mental_health_consequence phys_health_consequence  \
0       Somewhat easy                        No                      No   
1          Don't know                     Maybe                      No   
2  Somewhat difficult                        No                      No   
3  Somewhat difficult                       Yes                     Yes   
4          Don't know                        No                      No   

      coworkers supervisor mental_health_interview phys_health_interview  \
0  Some of them        Yes                      No                 Maybe   
1            No         No                      No                    No   
2           Yes        Yes                     Yes                   Yes   
3  Some of them         No                   Maybe                 Maybe   
4  Some of them        Yes                     Yes                   Yes   

  mental_vs_physical obs_consequence  
0                Yes              No  
1         Don't know              No  
2                 No              No  
3                 No             Yes  
4         Don't know              No  

[5 rows x 23 columns]